### ISSUE TITLE
Pre-launch todo's

### ISSUE THREAD

**Issue by thephilwells** [thephilwells/loggetter#1]
- [ ] Separate components into folders
- [ ] Validate form entries
- [ ] Add rows for multiple log keys
